sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5t7j95VZpuWXAYVSYzsp
    access-key-secret: wvgCAXfTS1okMJ1zN4bSmWB0ci8ONU
    bucket-name: some0nechen-sky-take-out
  redis:
    host: 192.168.119.88
    port: 6379
    password: cjd20001223
    database: 0
  wechat:
    appid: wx3a87e169671ee3ad
    secret: ee9452d1128df7bc858bfcf488b12b90